<?php

namespace Database\Seeders;

use App\Models\BlogCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BlogCategorySeeder extends Seeder
{
    /**
     * Seed missing categories without overwriting admin-managed records.
     */
    public function run(): void
    {
        foreach (self::names() as $name) {
            $slug = self::slugFor($name);

            BlogCategory::query()->firstOrCreate(
                ['slug' => $slug],
                [
                    'name' => $name,
                    'description' => "Articles, tutorials, news, and practical guides about {$name}.",
                    'is_active' => true,
                    'seo_title' => "{$name} Articles and Tutorials",
                    'seo_description' => "Explore {$name} news, tutorials, insights, and practical technical guides.",
                    'schema' => ['@type' => 'Blog'],
                ],
            );
        }
    }

    /** @return list<string> */
    public static function names(): array
    {
        return [
            'News',
            'Tools',
            'Trends',
            'Insights',
            'Blitzjs',
            'Snowpack',
            'Next.js',
            'Vue.js',
            'Svelte',
            'Backend',
            'Security',
            'AI',
            'Misc',
            'Mobile',
            'Alpine.js',
            'Architecture',
            'React',
            'Career',
            'daily.dev',
            'Testing',
            'Webdev',
            'gRPC',
            'Fastify',
            'GraphQL',
            'Tailwind CSS',
            'Weekly Picks',
            'Laravel',
            'JavaScript',
            'TypeScript',
            'Python',
            'PHP',
            'Java',
            'C',
            'C++',
            'C#',
            'Go',
            'Rust',
            'Ruby',
            'Swift',
            'Kotlin',
            'Dart',
            'Scala',
            'Elixir',
            'Erlang',
            'Haskell',
            'Clojure',
            'F#',
            'R',
            'MATLAB',
            'Julia',
            'Lua',
            'Perl',
            'Objective-C',
            'Solidity',
            'Zig',
            'Nim',
            'Crystal',
            'Shell Scripting',
            'SQL',
            'Angular',
            'Nuxt.js',
            'Node.js',
            'Express.js',
            'NestJS',
            'Django',
            'Flask',
            'FastAPI',
            'Ruby on Rails',
            'Symfony',
            'CodeIgniter',
            'Spring Boot',
            'ASP.NET Core',
            'Phoenix',
            'Deno',
            'Bun',
            'Astro',
            'Remix',
            'SolidJS',
            'HTMX',
            'WebAssembly',
            'HTML',
            'CSS',
            'Sass',
            'Bootstrap',
            'UI/UX',
            'Design Systems',
            'Accessibility',
            'Web Performance',
            'Progressive Web Apps',
            'Browser APIs',
            'REST APIs',
            'API Design',
            'Microservices',
            'Serverless',
            'WebSockets',
            'Android',
            'iOS',
            'React Native',
            'Flutter',
            'Ionic',
            'DevOps',
            'Cloud Computing',
            'AWS',
            'Microsoft Azure',
            'Google Cloud',
            'Docker',
            'Kubernetes',
            'Terraform',
            'Ansible',
            'CI/CD',
            'Linux',
            'Networking',
            'Observability',
            'Site Reliability Engineering',
            'Databases',
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'MongoDB',
            'Redis',
            'Elasticsearch',
            'Data Engineering',
            'Data Science',
            'Machine Learning',
            'Deep Learning',
            'Large Language Models',
            'MLOps',
            'Computer Vision',
            'Natural Language Processing',
            'Generative AI',
            'Cybersecurity',
            'Application Security',
            'Cloud Security',
            'DevSecOps',
            'Privacy',
            'Authentication',
            'Cryptography',
            'Ethical Hacking',
            'Git',
            'GitHub',
            'GitLab',
            'Visual Studio Code',
            'Open Source',
            'WordPress',
            'Shopify',
            'E-commerce',
            'Unit Testing',
            'Integration Testing',
            'End-to-End Testing',
            'Test Automation',
            'Blockchain',
            'Web3',
            'Games Blog',
            'Game Development',
            'Unity',
            'Unreal Engine',
            'Godot',
            'Indie Games',
            'PC Gaming',
            'Mobile Gaming',
            'Game Design',
            'AR/VR',
            'Internet of Things',
            'Robotics',
            'Embedded Systems',
            'Quantum Computing',
            'Product Management',
            'Startups',
            'Engineering Management',
            'Developer Experience',
            'Technical Writing',
            'Remote Work',
            'Freelancing',
            'Interview Preparation',
            'System Design',
            'Algorithms',
            'Data Structures',
            'Clean Code',
            'Software Craftsmanship',
        ];
    }

    private static function slugFor(string $name): string
    {
        return match ($name) {
            'C++' => 'cpp',
            'C#' => 'c-sharp',
            'F#' => 'f-sharp',
            'ASP.NET Core' => 'asp-net-core',
            'UI/UX' => 'ui-ux',
            'CI/CD' => 'ci-cd',
            'AR/VR' => 'ar-vr',
            default => Str::slug($name),
        };
    }
}
